packages:
  - packages/*
  - docs
  - '!playground'

catalog:
  '@antfu/eslint-config': ^6.2.0
  '@vitejs/plugin-vue': ^5.2.1
  '@vue/test-utils': ^2.4.6
  eslint: ^9.39.1
  jsdom: ^27.2.0
  typescript: ^5.9.3
  vite: ^7.2.4
  vite-plugin-dts: ^4.5.4
  vitepress: ^1.6.4
  vitest: 4.0.15
  vue: 3.5.24
  vue-tsc: ^2.2.0

cleanupUnusedCatalogs: true

linkWorkspacePackages: true

preferWorkspacePackages: true
