packages:
  - packages/*
  - docs

catalog:
  '@antfu/eslint-config': ^6.2.0
  '@vitejs/plugin-vue': ^5.2.1
  eslint: ^9.39.1
  typescript: ^5.9.3
  vite: ^7.2.4
  vite-plugin-dts: ^4.5.4
  vitepress: ^1.6.4
  vue: 3.5.24
  vue-tsc: ^2.2.0

cleanupUnusedCatalogs: true

linkWorkspacePackages: true

preferWorkspacePackages: true
