packages:
  - packages/*

catalog:
  '@eslint/js': ^9.39.1
  '@typescript-eslint/eslint-plugin': ^8.48.0
  '@typescript-eslint/parser': ^8.48.0
  '@vitejs/plugin-vue': ^5.2.1
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  prettier: ^3.7.1
  typescript: ^5.9.3
  vite: ^7.2.4
  vite-plugin-dts: ^4.5.4
  vue: ^3.5.13
  vue-tsc: ^2.2.0

cleanupUnusedCatalogs: true

linkWorkspacePackages: true

preferWorkspacePackages: true
